### ISSUE TITLE
Comparing to Hanami

### ISSUE THREAD

**Issue by makketagg** [pragmarb/pragmarb.org#1]
Hey @aldesantis, existing comparison on website looks awesome! But would be great to see [Hanami](http://hanamirb.org/) in list of frameworks. Thanks! 🙏

**Comment by aldesantis** [comment]
@makketagg hey, first of all, thanks for the feedback! :)

I don't think a comparison with Hanami would be fair or useful, because Pragma is not a Web framework, but rather an ecosystem of gems for the development of APIs.

In fact, Pragma needs a separate Web framework to work. Currently, the only official integration is [with Rails](https://github.com/pragmarb/pragma-rails), but I plan to write an Hanami integration in the not-too-distant future, since I absolutely love Hanami.

Let me know if that makes sense!

**Comment by makketagg** [comment]
@aldesantis learned more detailed info and examples 🤔and sorry - my bad. Agree with you 👍
